In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import copy
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, normalize
import scipy.cluster.hierarchy as shc
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from tqdm import tqdm
import torch
from torch import nn
from torch.utils.data import DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorboardX import SummaryWriter
import os
import time
from torcheval.metrics import R2Score
from sklearn.metrics import r2_score
import warnings
import pickle 
from scipy import stats


%matplotlib inline
pd.set_option('display.max_columns', None)
warnings.filterwarnings("ignore")

In [2]:
def swap_columns(df, col1, col2):
    col_list = list(df.columns)
    x, y = col_list.index(col1), col_list.index(col2)
    col_list[y], col_list[x] = col_list[x], col_list[y]
    df = df[col_list]
    return df

# pipeline

In [3]:
class Dataset(torch.utils.data.Dataset):
    def __init__(self, X, y):
        if not torch.is_tensor(X) or not torch.is_tensor(y):
            X = torch.from_numpy(X)
            y = torch.from_numpy(y)
            
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, i):
        return self.X[i], self.y[i]


class MLP(nn.Module):
    '''
        Multilayer Perceptron for regression.
    '''
    def __init__(self, n_in, n_out):
        super().__init__()
#         self.layers = nn.Sequential(
#             nn.Linear(n_in, 64),
#             nn.ReLU(),
#             nn.Linear(64, 32),
#             nn.ReLU(),
#             nn.Linear(32, n_out)
#         )
        
#         self.layers = nn.Sequential(
#             nn.Linear(n_in, 32),
#             nn.ReLU(),
#             nn.Linear(32, 64),
#             nn.ReLU(),
#             nn.Linear(64, 64),
#             nn.ReLU(),
#             nn.Linear(64, 32),
#             nn.ReLU(),
#             nn.Linear(32, 16),
#             nn.ReLU(),
#             nn.Linear(16, n_out)
#         )

        self.layers = nn.Sequential(
            nn.Linear(n_in, 32),
            nn.ReLU(),
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, n_out)
        )

#         self.layers = nn.Sequential(
#             nn.Linear(n_in, 32),
#             nn.ReLU(),
#             nn.Linear(32, 32),
#             nn.ReLU(),
#             nn.Linear(32, 32),
#             nn.ReLU(),
#             nn.Linear(32, n_out)
#         )


    def forward(self, x):
        '''
          Forward pass
        '''
        return self.layers(x)

In [4]:
def run_deep(X, y, idx, test_size, 
             train_batch_size, val_batch_size,
             learning_rate,
             tensorboard_path,
             print_iteration=1,
             n_epochs=100,
             tensorboard=True, 
             do_print=True):

    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=test_size)

    # Prepare dataset
    train_dataset = Dataset(X_train, y_train)
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=train_batch_size, shuffle=True)

    val_dataset = Dataset(X_val, y_val)
    val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=val_batch_size, shuffle=True)

    # Initialize the MLP
    mlp = MLP(n_in=X_train.shape[1], n_out=1)

    # Define the loss function and optimizer
    loss_function = nn.MSELoss(reduction='sum')
    optimizer = torch.optim.Adam(mlp.parameters(), lr=learning_rate)    
    
    if tensorboard:
        writer = SummaryWriter(tensorboard_path)
    
    # Run the training loop
    total_iteration = 0
    best_val_results = dict(loss = np.inf, corr = -np.inf, r2 = -np.inf)
    for epoch in range(n_epochs): 
        outputs_train_arr = np.array([])
        targets_train_arr = np.array([])

        current_loss = 0.0
        n_train_data = 0
        for inputs, targets in train_loader:
            total_iteration += 1
            inputs, targets = inputs.float(), targets.float()
            targets = targets.reshape((targets.shape[0], 1))
            n_train_data += inputs.shape[0]
            
            optimizer.zero_grad()
            
            outputs = mlp(inputs)
            loss = loss_function(outputs, targets)
            loss.backward()
            optimizer.step()
            current_loss += loss.item()
            
            outputs_detach = torch.detach(outputs)
            targets_detach = torch.detach(targets)
            outputs_train_arr = np.append(outputs_train_arr, torch.Tensor.numpy(outputs_detach).reshape(1,-1)[0])
            targets_train_arr = np.append(targets_train_arr, torch.Tensor.numpy(targets_detach).reshape(1,-1)[0])
                       
            if total_iteration % print_iteration == 0:
                loss_val = 0
                n_val_data = 0
                outputs_val_arr = np.array([])
                targets_val_arr = np.array([])

                for inputs_val, targets_val in val_loader:
                    inputs_val, targets_val = inputs_val.float(), targets_val.float()
                    targets_val = targets_val.reshape((targets_val.shape[0], 1))
                    n_val_data += inputs_val.shape[0]
                    outputs_val = mlp(inputs_val)
                    loss_val += loss_function(outputs_val, targets_val).item()
                    outputs_val_detach = torch.detach(outputs_val)
                    targets_val_detach = torch.detach(targets_val)
                    outputs_val_arr = np.append(outputs_val_arr, torch.Tensor.numpy(outputs_val_detach).reshape(1,-1)[0])
                    targets_val_arr = np.append(targets_val_arr, torch.Tensor.numpy(targets_val_detach).reshape(1,-1)[0])
                    
                corrcoef = np.corrcoef(targets_val_arr, outputs_val_arr)[0, 1]
                r_squared = r2_score(targets_val_arr, outputs_val_arr)
                train_loss = current_loss / n_train_data
                val_loss = loss_val / n_val_data
                
                if tensorboard:
                    writer.add_scalars(f'{str(idx)}_loss', {
                        'train': train_loss,
                        'validation': val_loss,
                    }, total_iteration)
                    writer.add_scalars(f'{str(idx)}_corr-R', {
                        'corr': corrcoef,
                        'r': r_squared,
                    }, total_iteration)
                
                if val_loss < best_val_results['loss']:
                    best_val_results['loss']
                best_val_results['loss'] = val_loss if val_loss < best_val_results['loss'] else best_val_results['loss']
                best_val_results['corr'] = corrcoef if corrcoef > best_val_results['corr'] else best_val_results['corr']
                best_val_results['r2'] = r_squared if r_squared > best_val_results['r2'] else best_val_results['r2']
                
                current_loss = 0.0
                n_train_data = 0
        
        corrcoef = np.corrcoef(targets_train_arr, outputs_train_arr)[0, 1]
        r_squared = r2_score(targets_train_arr, outputs_train_arr)
        
    print_str = (f"best of {str(idx).rjust(3)} => loss: {str(round(best_val_results['loss'], 2)).rjust(11)}, " + 
                 f"corr: {str(round(best_val_results['corr'], 2)).rjust(5)}, " + 
                 f"r2: {str(round(best_val_results['r2'], 2)).rjust(5)}")
    if do_print:
        print(print_str)
    
    if tensorboard:
        writer.add_text(str(idx), print_str)
        del writer
        
    return print_str, best_val_results

# run pipeline

In [6]:
# data

# df_to_run = pd.read_csv('data/deep_test_retest_imputed.csv')
df_to_run = pd.read_csv('../../data/deep_test_retest_imputed_measures_standardized.csv')
data_arr = df_to_run.iloc[:,2:].to_numpy()
X = data_arr[:, :12]
y_total = data_arr[:, 12:]

In [36]:
X_df.drop(columns='age').to_numpy()

array([[  0. ,   4. ,   0. , ...,  50. ,  80. , 126. ],
       [  0. ,   0.5,   0. , ...,  61. ,  80. , 135. ],
       [  1. ,   0. ,   0. , ...,  42. ,  40. ,  84. ],
       ...,
       [  1. ,   3. ,   0. , ...,  61. ,  72. , 129. ],
       [  0. ,   1. ,   0. , ...,  66. ,  73. , 134. ],
       [  0. ,   0. ,   0. , ...,  64. ,  66. , 126. ]])

In [18]:
array = np.arange(X.shape[1])
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
for col, arr in zip(X_df.columns, X.T):
    print(col, type(arr))

age <class 'numpy.ndarray'>
gender <class 'numpy.ndarray'>
musicAllYears <class 'numpy.ndarray'>
musicFormal <class 'numpy.ndarray'>
cog_wm_omissions <class 'numpy.ndarray'>
cog_wm_rt <class 'numpy.ndarray'>
cog_flex_totalperf <class 'numpy.ndarray'>
cog_gonogo_errors <class 'numpy.ndarray'>
cog_gonogo_rt <class 'numpy.ndarray'>
wasiMatrixT <class 'numpy.ndarray'>

In [28]:
df_to_run

,subject_session,ageGroup,age,gender,musicAllYears,musicFormal,cog_wm_omissions,cog_wm_rt,cog_flex_totalperf,cog_gonogo_errors,cog_gonogo_rt,wasiMatrixT,wasiVocabT,wasiFSIQ2,BAT_all_dprime,BAT_fast_dprime,BAT_med_dprime,BAT_slow_dprime,BAT_all_hits,BAT_fast_hits,BAT_med_hits,BAT_slow_hits,BAT_all_fa,BAT_fast_fa,BAT_med_fa,BAT_slow_fa,DurDisc_threshold,Anisochrony_tones_threshold,Anisochrony_music_threshold,Unpaced_spontaneous_right_CV_iti,Unpaced_spontaneous_final_right_CV_iti,Unpaced_fast_CV_iti,Unpaced_slow_CV_iti,Unpaced_spontaneous_right_mean_iti,Unpaced_spontaneous_final_right_mean_iti,Unpaced_fast_mean_iti,Unpaced_slow_mean_iti,Paced_metro_450_mean_CV_iti,Paced_metro_450_vecDirPct,Paced_metro_450_mean_vector_direction,Paced_metro_450_vecLenLogit,Paced_metro_600_mean_CV_iti,Paced_metro_600_vecDirPct,Paced_metro_600_mean_vector_direction,Paced_metro_600_vecLenLogit,Paced_metro_750_mean_CV_iti,Paced_metro_750_vecDirPct,Paced_metro_750_mean_vector_direction,Paced_metro_750_vecLenLogit,Paced_music_badine_mean_CV_iti,Paced_music_badine_vecDirPct,Paced_music_badine_mean_vector_direction,Paced_music_badine_vecLenLogit,Paced_music_ross_mean_CV_iti,Paced_music_ross_vecDirPct,Paced_music_ross_mean_vector_direction,Paced_music_ross_vecLenLogit,Adaptive_adaptation_index_acceleration,Adaptive_adaptation_index_deceleration,Adaptive_iso_600_CV_iti,Adaptive_minus_30_dprime2,Adaptive_minus_75_dprime2,Adaptive_plus_30_dprime2,Adaptive_plus_75_dprime2,SyncCont_metro_450_mean_CV_iti,SyncCont_metro_600_mean_CV_iti,SyncCont_metro_750_mean_CV_iti,SyncCont_metro_450_mean_mean_iti,SyncCont_metro_600_mean_mean_iti,SyncCont_metro_750_mean_mean_iti
0,A03_PRE,Age_22_29,22,0,4.0,0.0,44.0,43.0,58.0,40.0,52.0,50.0,80.0,126.0,-1.117825,-1.159666,-1.162388,-0.384372,0.559051,0.621256,0.162754,0.742530,3.082329,2.706190,2.519201,2.368778,0.286102,-1.390923,-0.369176,0.600602,5.903224,0.467735,0.445230,0.480356,0.748724,0.649342,1.677309,1.215221,-0.777824,-0.541681,-1.594148,3.376893,0.464756,0.466648,-0.639599,1.294873,-0.315105,-0.315105,-0.181463,0.544694,-1.002731,-0.831893,-0.071738,0.656663,-0.788603,-0.585061,-0.127144,-0.346649,-1.564702,2.078664,-2.211761,-1.562522,-2.168695,-4.136652,2.259454,3.886848,2.088498,-1.697993,0.775256,0.443109
1,A04_PRE,Age_22_29,22,0,0.5,0.0,36.0,41.0,61.0,47.0,43.0,61.0,80.0,135.0,0.824157,0.826215,0.490315,0.958353,0.705587,0.621256,0.542514,0.742530,-0.650975,-0.657117,-0.463733,-0.422159,-0.601409,-0.487563,-0.779771,-0.133470,-0.555041,0.282094,-0.146414,-0.749148,-0.507287,-0.623180,0.028125,0.011330,0.901992,0.850409,0.335237,-0.570282,0.855084,0.812029,-0.094977,0.892137,1.251825,1.251825,0.205237,-0.019815,0.414078,0.385741,0.264570,-0.587560,1.261220,1.119985,0.998464,0.256306,0.637831,-0.535411,-0.956548,0.721844,-0.133906,0.718253,-0.611379,-0.579382,-0.148945,0.273827,0.229866,0.942502
2,A07_PRE,Age_22_29,22,1,0.0,0.0,44.0,43.0,46.0,50.0,49.0,42.0,40.0,84.0,-0.847244,-1.086691,-0.684206,0.121230,0.265980,-0.121754,0.162754,0.742530,1.215677,1.024537,1.027734,0.973310,0.940376,1.493668,1.291464,2.261900,0.261598,4.106214,0.263632,-0.836689,-1.461212,-0.584930,-1.256149,0.200395,1.016455,0.945267,0.781786,0.200050,0.731981,0.703101,-0.723369,0.599696,0.715970,0.715970,0.411902,-0.417636,0.533722,0.488565,0.934209,-0.080005,0.942770,0.855098,-0.487952,0.226099,-2.299490,0.714698,-0.760034,-0.274275,-1.185116,-1.954857,-0.116883,-0.305044,-0.062222,-1.550100,0.161585,-1.036417
3,A08_PRE,Age_18_21,18,1,4.0,0.0,48.0,39.0,48.0,50.0,52.0,68.0,80.0,142.0,-0.401702,0.245421,-0.684206,0.238933,0.559051,0.992762,0.162754,0.309388,0.749014,1.024537,1.027734,-0.422159,-0.183737,-1.054677,-0.647978,1.842967,1.307729,0.766394,0.918956,0.739276,0.924970,1.033904,-0.391347,2.749706,0.668256,0.656709,-0.714841,1.577136,0.484490,0.484109,-0.124601,2.329984,0.401806,0.401806,-0.350257,0.378154,-0.167554,-0.114125,-0.098478,-0.139704,0.336646,0.350923,0.684235,0.075926,-0.141362,2.995237,-1.254390,-3.487885,-2.068581,-3.926704,2.732820,1.603161,2.964519,-1.755292,-1.466280,-1.787821
4,A09_PRE,Age_22_29,25,1,3.0,0.0,50.0,41.0,38.0,50.0,44.0,55.0,54.0,108.0,1.022252,1.496570,1.170720,0.121230,0.998658,0.992762,0.922274,0.742530,-0.184312,-0.657117,-0.463733,0.973310,0.556697,-0.082395,-0.647978,0.439298,0.345932,-0.683870,-0.324136,-0.932118,-0.235174,-1.166064,-0.931669,0.497259,-0.959490,-0.692230,-1.145763,1.323672,-2.032065,-1.742660,-2.983256,0.274721,0.245460,0.245460,0.163434,-0.606549,-0.509031,-0.407598,1.018473,-0.538239,0.476470,0.467229,1.092894,-0.471437,1.450497,-0.244461,1.242395,0.721844,-0.428448,0.718253,0.143068,-0.013258,-0.364366,-0.801872,0.550458,-0.342022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,F03_POST,Age_55_87,71,0,0.0,0.0,73.0,59.0,74.0,50.0,54.0,79.0,80.0,142.0,1.078104,1.496570,1.170720,0.238933,0.852122,0.992762,0.922274,0.309388,-0.650975,-0.657117,-0.463733,-0.422159,-0.614787,0.070995,-0.624818,-0.522947,-0.860048,-0.970000,-0.020123,0.951261,1.185510,-0.720054,-0.248785,-0.889385,-0.621891,-0.412457,0.838787,-1.601046,-0.195073,-0.117201,1.178641,-1.255202,0.347510,0.347510,1.177107,-0.802624,-0.148361,-0.097631,1.144405,-0.727221,0.450650,0.445751,1.254118,-0.997892,-0.061820,-0.403443,0.608072,-1.189575,0.494915,-0.122000,-0.465434,-0.745674,0.698608,-1.119529,-0.056266,-0.107707
115,F07_POST,Age_55_87,87,1,0.0,0.0,76.0,60.0,79.0,50.0,44.0,61.0,60.0,118.0,0.265394,-0.287932,1.170720,0.238933,0.119445,-0.864764,0.922274,0.309388,-0.650975,-0.657117,-0.463733,-0.422159,2.851145,0.400996,-0.558646,-0.110802,0.119129,-0.549036,0.118427,-0.676162,-3.015761,0.401577,-0.269424,-0.562337,0.908039,0.855421,0.473332,-0.408444,-0.288741,-0.200082,0.341341,-0.176500,0.340714,0.340714,0.536873,0.536435,0.153969,0.162198,-0.678206,0.000014,0.218172,0.252376,0.135498,-0.032348,-2.250200,1.376449,-0.540586,0.721844,-1.185116,0.718253,0.430985,0.448597,-0.438333,2.651938,1.898262,1.523676
116,F08_POST,Age_55_87,72,1,3.0,0.0,69.0,53.0,63.0,50.0,43.0,61.0,72.0,129.0,0.642079,0.449073,0.490315,0.958353,0.559051,0.249751,0.542514,0.742530,-0.650975,-0.657117,-0.463733,-0.422159,-1.183659,-0.289562,0.879772,-0.177685,-0.043611,0.201722,-0.046610,-0.134301,-0.262830,0.458949,-0.633565,0.028049,1.777377,1.575855,0.447188,0.023921,1.172575,1.092960,0.164398,1.174698,-0.447326,-0.447326,-0.208115,0.369073,0.402837,0.376080,0.022180,-0.493222,0.622922,0.589048,0.890827,-0.322346,-1.446464,-0.777110,1.242395,0.721844,1.051685,0.718253,0.153293,-0.900888,-0.321093,0.477596,-0.267783,-0.334134
117,F11_POST,Age_55_87,80,0,1.0,0.0,73.0,57.0,62.0,50.0,65.0,66.0,73.0,134.0,-0.454592,0.245421,0.107518,-0.471261,0.265980,0.992762,0.162754,-0.556898,0.282351,1.024537,-0.463733,-0.422159,0.061258,-0.575564,1.993636,0.607921,-0.512392,0.334101,-0.133729,0.723972,1.380906,0.555191,0.947619,0.039866,-0.723132,-0.496357,-0.919163,0.119983,0.245461,0.272606,-0.486713,-0.680482,0.797968,0.797968,-0.267351,-0.070619,-0.143514,-0.093465,-0.304120,0.080739,-0.596412,-0.425196,-0.001269,-0.314285,-0.037687,0.178005,-0.738682,-1.759817,0.161371,-0.122000,0.053994,0.538645,-0.329120,1.286986,1.097867,0.598121
118,F13_POST,Age_55_87,80,0,0.0,0.0,44.0,51.0,59.0,50.0,57.0,64.0,66.0,126.0,-0.222937,-0.485552,-0.640536,0.238933,-0.759768,-1.236269,-0.976525,0.309388,-0.650975,-0.657117,-0.463733,-0.422159,-0.266026,0.598997,0.366111,0.609217,-1.216383,-0.355900,-0.128728,0.405371,1.701097,0.908449,0.199373,0.843448,0.154041,0.230571,0.367161,0.128088,0.726763,0.698484,0.590090,0.324020,0.607881,0.607881,0.415223,0.360133,0.118747,0.131927,-0.050899,-0.076230,0.289195,0.311453,0.634712,-1.374033,0.091009,-1.261219,-0.212687,0.721844,-0.133906,0.718253,-0.561592,-1.293487,-1.017398,0.965910,0.561786,0.013499

In [31]:
X_df = df_to_run.iloc[:, 2:14]
X_df.columns

TypeError: 'Index' object is not callable

In [7]:
all_str = str()
for idx in range(56):
    y = y_total[:, idx]

    tensorboard_path = os.path.join('tensorboard5/', str(idx) + '_' + str(int(round(time.time() % 1, 5) * 1e5)))
    print_str, _ = run_deep(X, y, idx, 0.2, 
                         train_batch_size=10, val_batch_size=5, 
                         learning_rate=1e-3, 
                         tensorboard_path=tensorboard_path, 
                         print_iteration=1, 
                         n_epochs=100,
                         tensorboard=False)
    all_str += print_str + '\n'

f = open("1e-3_fancynet3.txt", "w")
f.write(all_str)
f.close()

best of   0 => loss:        0.61, corr:  0.45, r2:  0.17
best of   1 => loss:        0.45, corr:  0.61, r2:  0.36
best of   2 => loss:        0.51, corr:  0.18, r2: -0.16
best of   3 => loss:        0.42, corr:   0.5, r2:  0.24
best of   4 => loss:      204.36, corr:   0.3, r2:  0.03
best of   5 => loss:       243.3, corr:  0.34, r2:  0.09
best of   6 => loss:      252.73, corr:  0.29, r2: -0.28
best of   7 => loss:      130.24, corr:  0.49, r2:  0.22
best of   8 => loss:       99.66, corr:  0.43, r2:  0.15
best of   9 => loss:      117.57, corr:  0.68, r2:  0.38
best of  10 => loss:       23.17, corr:  0.34, r2:   0.1
best of  11 => loss:       31.98, corr:  0.51, r2:  0.24
best of  12 => loss:      178.75, corr:  0.15, r2: -0.25
best of  13 => loss:        9.56, corr:  0.59, r2:  0.31
best of  14 => loss:       43.94, corr:  0.28, r2: -0.04
best of  15 => loss:         0.0, corr:  0.21, r2: -2.89
best of  16 => loss:         0.0, corr:  0.49, r2: -1.49
best of  17 => loss:         0.0, corr:  0.54, r2: -0.53
best of  18 => loss:         0.0, corr:  0.47, r2: -4.68
best of  19 => loss:     9622.44, corr:  0.66, r2:  0.42
best of  20 => loss:     8418.38, corr:  0.52, r2:  0.24
best of  21 => loss:    10215.22, corr:  0.43, r2:  0.16
best of  22 => loss:   158737.07, corr:  0.17, r2:   0.0
best of  23 => loss:         0.0, corr:  0.27, r2: -3.87
best of  24 => loss:       35.91, corr:  0.32, r2:  0.09
best of  25 => loss:      763.56, corr:  0.63, r2:  0.23
best of  26 => loss:        0.41, corr:  0.68, r2:   0.3
best of  27 => loss:         0.0, corr:  0.25, r2: -1.16
best of  28 => loss:       43.18, corr:  0.28, r2:  -0.0
best of  29 => loss:       215.3, corr:  0.24, r2:  0.03
best of  30 => loss:        0.28, corr:  0.61, r2:  0.36
best of  31 => loss:         0.0, corr:  0.45, r2: -0.82
best of  32 => loss:       15.15, corr:  0.05, r2: -0.08
best of  33 => loss:      384.34, corr:   0.7, r2:  0.27
best of  34 => loss:        0.32, corr:  0.79, r2:  0.59
best of  35 => loss:         0.0, corr:  0.17, r2: -6.12
best of  36 => loss:       22.61, corr:  0.67, r2:  0.27
best of  37 => loss:      414.76, corr:  0.48, r2:  0.15
best of  38 => loss:        1.65, corr:   0.3, r2:  0.01
best of  39 => loss:         0.0, corr:  0.27, r2: -0.93
best of  40 => loss:       24.17, corr:  0.32, r2:  0.04
best of  41 => loss:      936.47, corr:   0.1, r2:  0.01
best of  42 => loss:        1.93, corr:  0.58, r2:  0.28
best of  43 => loss:        0.23, corr: -0.02, r2: -0.22
best of  44 => loss:        0.08, corr:  0.59, r2:  0.21
best of  45 => loss:         0.0, corr:  0.25, r2: -1.59
best of  46 => loss:        0.58, corr:  0.24, r2:  0.02
best of  47 => loss:         0.2, corr:  0.43, r2:  0.18
best of  48 => loss:        0.29, corr:  0.61, r2:  0.32
best of  49 => loss:        0.09, corr:  0.28, r2: -0.18
best of  50 => loss:         0.0, corr:  0.44, r2:  -0.9
best of  51 => loss:         0.0, corr:   0.3, r2: -0.16
best of  52 => loss:         0.0, corr:   0.3, r2: -1.06
best of  53 => loss:     1975.62, corr:  0.21, r2: -4.63
best of  54 => loss:     3774.04, corr: -0.01, r2: -10.74
best of  55 => loss:     3172.59, corr:  0.29, r2: -0.73

# significance test

In [38]:
# data

df_to_run = pd.read_csv('../data/deep_test_retest_imputed.csv')
# df_to_run = pd.read_csv('data/deep_test_retest_imputed_measures_standardized.csv')
data_arr = df_to_run.iloc[:,2:].to_numpy()
X = data_arr[:, :12]
y_total = data_arr[:, 12:]

In [65]:
n_shuff = 10
results_df = dict()
results_df['name'] = ['idx', 'loss', 'p_loss', 'sig_loss', 'corr', 'p_corr', 'sig_corr', 'r2', 'p_r2', 'sig_r2']
for idx in range(5):
    y = copy.deepcopy(y_total[:, idx])

    tensorboard_path = os.path.join('tensorboard5/', str(idx) + '_' + str(int(round(time.time() % 1, 5) * 1e5)))
    _, best_r = run_deep(X, y, idx, 0.2, 
                         train_batch_size=10, val_batch_size=5, 
                         learning_rate=1e-3, 
                         tensorboard_path=tensorboard_path, 
                         print_iteration=1, 
                         n_epochs=100,
                         tensorboard=False,
                         do_print=False)
    
    all_r = dict(loss = list(), corr = list(), r2 = list())
    for i in tqdm(range(n_shuff)):
        np.random.shuffle(y)
        tensorboard_path = os.path.join('tensorboard5/', str(idx) + '_' + str(int(round(time.time() % 1, 5) * 1e5)))
        _, shuf_r = run_deep(X, y, idx, 0.2, 
                             train_batch_size=10, val_batch_size=5, 
                             learning_rate=1e-3, 
                             tensorboard_path=tensorboard_path, 
                             print_iteration=1, 
                             n_epochs=100,
                             tensorboard=False,
                             do_print=False)
        all_r['loss'].append(shuf_r['loss'])
        all_r['corr'].append(shuf_r['corr'])
        all_r['r2'].append(shuf_r['r2'])
    
    all_r['best_results'] = best_r
    col_name = df_to_run.columns[idx + 14]
    with open('results/' + col_name + '.pkl', 'wb') as f:
        pickle.dump(all_r, f)

    p_loss = 0
    p_corr = 0
    p_r2 = 0
    for i in range(n_shuff):
        p_loss += 1 if all_r['loss'][i] < best_r['loss'] else 0
        p_corr += 1 if all_r['corr'][i] > best_r['corr'] else 0
        p_r2 += 1 if all_r['r2'][i] > best_r['r2'] else 0
        
    print(p_loss, p_corr, p_r2, col_name)
    p_loss /= n_shuff
    sig_loss = 'Yes' if p_loss <= 0.05 else 'No'
    p_corr /= n_shuff
    sig_corr = 'Yes' if p_corr <= 0.05 else 'No'
    p_r2 /= n_shuff
    sig_r2 = 'Yes' if p_r2 <= 0.05 else 'No'
    
    results_df[col_name] = [int(idx), round(best_r['loss'], 4), round(p_loss, 3), sig_loss, 
                                               round(best_r['corr'], 4) , round(p_corr, 3), sig_corr,
                                               round(best_r['r2'], 4) , round(p_r2, 3), sig_r2]
    
    print(f'idx {idx} \np_value of loss: {p_loss} \np_value of corr: {p_corr} \np_value of r2: {p_r2}')
    print('\n================\n')

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:07<00:00,  1.42it/s]

1 0 0 BAT_all_dprime
idx 0
p_value of loss: 0.1
p_value of corr: 0.0
p_value of r2: 0.0

================

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:07<00:00,  1.43it/s]

1 2 2 BAT_fast_dprime
idx 1
p_value of loss: 0.1
p_value of corr: 0.2
p_value of r2: 0.2

================

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:07<00:00,  1.42it/s]

6 3 4 BAT_med_dprime
idx 2
p_value of loss: 0.6
p_value of corr: 0.3
p_value of r2: 0.4

================

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.43it/s]

6 1 1 BAT_slow_dprime
idx 3
p_value of loss: 0.6
p_value of corr: 0.1
p_value of r2: 0.1

================

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.43it/s]

3 1 6 BAT_all_hits
idx 4
p_value of loss: 0.3
p_value of corr: 0.1
p_value of r2: 0.6

================

# significance test v2

In [272]:
a = np.random.normal(loc=0, size=100)
b = np.random.normal(loc=0, size=100)

stats.ttest_ind(b, a, alternative='less').pvalue

0.04762672498504203

In [108]:
# data

df_to_run = pd.read_csv('../data/deep_test_retest_imputed.csv')
# df_to_run = pd.read_csv('data/deep_test_retest_imputed_measures_standardized.csv')
data_arr = df_to_run.iloc[:,2:].to_numpy()
X = data_arr[:, :12]
y_total = data_arr[:, 12:]

In [116]:
n_shuff = 10
results_df = dict()
results_df['name'] = ['idx', 
                      'loss_null', 'loss_alternative', 'p_loss', 'sig_loss', 
                      'corr_null', 'corr_alternative', 'p_corr', 'sig_corr', 
                      'r2_null', 'r2_alternative', 'p_r2', 'sig_r2']
for idx in range(5):
    y = copy.deepcopy(y_total[:, idx])
    alternative_res = dict(loss = list(), corr = list(), r2 = list())
    for i in range(n_shuff):
        tensorboard_path = os.path.join('tensorboard5/', str(idx) + '_' + str(int(round(time.time() % 1, 5) * 1e5)))
        _, res = run_deep(X, y, idx, 0.2, 
                             train_batch_size=10, val_batch_size=5, 
                             learning_rate=1e-3, 
                             tensorboard_path=tensorboard_path, 
                             print_iteration=1, 
                             n_epochs=100,
                             tensorboard=False,
                             do_print=False)
        alternative_res['loss'].append(res['loss'])
        alternative_res['corr'].append(res['corr'])
        alternative_res['r2'].append(res['r2'])
    
    null_res = dict(loss = list(), corr = list(), r2 = list())
    for i in tqdm(range(n_shuff)):
        np.random.shuffle(y)
        tensorboard_path = os.path.join('tensorboard5/', str(idx) + '_' + str(int(round(time.time() % 1, 5) * 1e5)))
        _, shuf_r = run_deep(X, y, idx, 0.2, 
                             train_batch_size=10, val_batch_size=5, 
                             learning_rate=1e-3, 
                             tensorboard_path=tensorboard_path, 
                             print_iteration=1, 
                             n_epochs=100,
                             tensorboard=False,
                             do_print=False)
        null_res['loss'].append(shuf_r['loss'])
        null_res['corr'].append(shuf_r['corr'])
        null_res['r2'].append(shuf_r['r2'])
    
    
    all_res = dict(alternative=alternative_res, null=null_res)
    
    col_name = df_to_run.columns[idx + 14]
    with open('results/' + col_name + '.pkl', 'wb') as f:
        pickle.dump(all_res, f)

    p_loss = stats.ttest_ind(alternative_res['loss'], null_res['loss'], alternative='less').pvalue
    p_corr = stats.ttest_ind(alternative_res['corr'], null_res['corr'], alternative='greater').pvalue
    p_r2 = stats.ttest_ind(alternative_res['r2'], null_res['r2'], alternative='greater').pvalue

    sig_loss = 'Yes' if p_loss <= 0.05 else 'No'
    sig_corr = 'Yes' if p_corr <= 0.05 else 'No'
    sig_r2 = 'Yes' if p_r2 <= 0.05 else 'No'
    
    
    results_df[col_name] = [int(idx), 
                            round(np.mean(null_res['loss']), 4), round(np.mean(alternative_res['loss']), 4), round(p_loss, 3), sig_loss, 
                            round(np.mean(null_res['corr']), 4), round(np.mean(alternative_res['corr']), 4), round(p_corr, 3), sig_corr,
                            round(np.mean(null_res['r2']), 4), round(np.mean(alternative_res['r2']), 4) , round(p_r2, 3), sig_r2]
    
    print(f'idx {idx} \np_value of loss: {p_loss} \np_value of corr: {p_corr} \np_value of r2: {p_r2}')
    print('\n================\n')

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.44it/s]

idx 0
p_value of loss: 0.0758283425650643
p_value of corr: 0.0030275591244975993
p_value of r2: 0.00012036604986994324

================

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.44it/s]

idx 1
p_value of loss: 0.009732692797546046
p_value of corr: 0.0002578654558731825
p_value of r2: 0.0011933489142811444

================

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.44it/s]

idx 2
p_value of loss: 0.8667914709297857
p_value of corr: 0.004904476514091272
p_value of r2: 0.03894724407054126

================

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:07<00:00,  1.43it/s]

idx 3
p_value of loss: 0.0184246701971701
p_value of corr: 0.00046407838815542846
p_value of r2: 0.0011241638437281287

================

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.44it/s]

idx 4
p_value of loss: 0.5957577475191669
p_value of corr: 0.0001770622899225477
p_value of r2: 0.5338939196270962

================

In [117]:
pd.DataFrame(results_df)

,name,BAT_all_dprime,BAT_fast_dprime,BAT_med_dprime,BAT_slow_dprime,BAT_all_hits
0,idx,0,1,2,3,4
1,loss_null,0.7915,0.629,0.5352,0.5436,261.1651
2,loss_alternative,0.6552,0.4659,0.6131,0.4126,284.3998
3,p_loss,0.076,0.01,0.867,0.018,0.596
4,sig_loss,No,Yes,No,Yes,No
5,corr_null,0.3925,0.184,0.1253,0.3067,0.1678
6,corr_alternative,0.5768,0.4924,0.3495,0.5487,0.4483
7,p_corr,0.003,0.0,0.005,0.0,0.0
8,sig_corr,Yes,Yes,Yes,Yes,Yes
9,r2_null,0.0093,-0.055,-0.1276,0.0303,-0.2174
10,r2_alternative,0.2891,0.2024,0.0356,0.2714,-0.2509
11,p_r2,0.0,0.001,0.039,0.001,0.534
12,sig_r2,Yes,Yes,Yes,Yes,No

In [115]:
all_res

{'alternative': {'loss': [144.6947021484375,
   92.77509657541911,
   210.32421239217123,
   149.25953102111816,
   100.41545232137044,
   188.40666516621908,
   210.6069793701172,
   123.49387486775716,
   158.8606859842936,
   173.4744784037272],
  'corr': [0.5011272500073093,
   0.5321664680610092,
   0.5007289658751364,
   0.40957389927775456,
   0.5955573548215631,
   0.3910435094215344,
   0.4299930070391786,
   0.5833155251476821,
   0.16974276822598033,
   0.4413905224729217],
  'r2': [0.1955723200149091,
   0.25362383264387156,
   0.2388478200253179,
   0.041781467801786154,
   0.3543207407113136,
   0.09394382319709038,
   0.16687318973617393,
   0.27649113659563296,
   -0.8911432920242215,
   0.06869470113911469]},
 'null': {'loss': [303.03292083740234,
   442.87876383463544,
   187.95297876993814,
   234.6160888671875,
   233.20376904805502,
   230.94719314575195,
   225.9209950764974,
   260.98717244466144,
   267.67936579386395,
   255.38497670491537],
  'corr': [-0.0499854006028681,
   -0.2833098090327361,
   0.2237440186517468,
   0.06284987628257753,
   0.3209130175164797,
   0.06434486352573106,
   0.2888634363581037,
   0.1224257971511351,
   0.2394592891255643,
   0.387065816253874],
  'r2': [-0.5019839206813697,
   -0.7876035719394245,
   -0.32740756741436616,
   -0.15028803480220487,
   0.04890696527442273,
   -0.20708500988887923,
   -0.00993920914468549,
   -0.6819985793963765,
   -0.31574635690762154,
   -0.06713608366043777]}}